# Generated by Django 2.2.8 on 2020-01-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='meaow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figaro', models.CharField(max_length=33)),
            ],
        ),
    ]
