# Generated by Django 2.2.8 on 2020-02-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_meaow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='meaow',
        ),
    ]
